# Site settings
title: Wei Huo
description: 'Business Card Page'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/touxiang.jpg'
bkimage: '/images/bk3.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Wei Huo'
  email: 3111314916@qq.com
  orcid: 0009-0003-1684-4873
  # twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  hw-star
  # linkedin_username:  thomas-zühlke-889182165
  # meetup_name: Azure-Meetup-Rostock-MV

skills:
  frontend:
    - Vue
    - JavaScript
    - CSS
    - ElementUI
  backend:
    - Java
    - SpringBoot
    - Redis
    - MySQL
  ai:
    - Python
    - PyTorch
  others:
    - Linux
    - Crawler
  
notes:
    - title: Java 学习笔记
      url: https://yourdomain.com/notes/java
    - title: 通讯系统
      url: https://yourdomain.com/notes/communication
      
publications:
  - title: "HES-UNet: A U-Net for Hepatic Echinococcosis Lesion Segmentation"
    authors: "Jiayan Chen, Kai Li, Zhanjin Wang, Zhan Wang, Jianqiang Huang"
    venue: "arXiv 2024"
    demo: "#"
    pdf: "#"
    code: "#"

fun:
  - 🌌 I love stargazing in Xining's clear skies.
  - 🎮 Big fan of strategy games—especially Civilization VI.
  - 📷 Enjoy taking photos of landscapes and architecture.
  - 📚 Learning addict—frequently explore new topics in AI and philosophy.

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
